modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/MORIMORI0317/SimpleTranslation/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "simpletranslation"
version = "${version}"
displayName = "Simple Translation"
authors = "MORIMORI0317"
description = '''
The Ikisugi Simple Translation MOD
'''
logoFile = "logo.png"

[[dependencies.simpletranslation]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simpletranslation]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simpletranslation]]
modId = "architectury"
mandatory = true
versionRange = "[2.3.23,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.simpletranslation]]
modId = "cloth_config"
mandatory = true
versionRange = "[5.0.38,)"
ordering = "AFTER"
side = "BOTH"